`define LATTICE_FAMILY "ECP2"
`define LATTICE_FAMILY_ECP2
`define LATTICE_DEVICE "All"
`ifndef SYSTEM_CONF
`define SYSTEM_CONF
`timescale 1ns / 100 ps
`define CFG_EBA_RESET 32'h0
`define CFG_DISTRAM_POSEDGE_REGISTER_FILE
`define MULT_ENABLE
`define CFG_PL_MULTIPLY_ENABLED
`define SHIFT_ENABLE
`define CFG_PL_BARREL_SHIFT_ENABLED
`define CFG_MC_DIVIDE_ENABLED
`define CFG_SIGN_EXTEND_ENABLED
`define CFG_ICACHE_ENABLED
`define CFG_ICACHE_BASE_ADDRESS 32'h0
`define CFG_ICACHE_LIMIT 32'h27ffff
`define CFG_ICACHE_SETS 512
`define CFG_ICACHE_ASSOCIATIVITY 1
`define CFG_ICACHE_BYTES_PER_LINE 16
`define CFG_ICACHE_AUTO
`define CFG_DCACHE_ENABLED
`define CFG_DCACHE_BASE_ADDRESS 32'h0
`define CFG_DCACHE_LIMIT 32'h27ffff
`define CFG_DCACHE_SETS 512
`define CFG_DCACHE_ASSOCIATIVITY 1
`define CFG_DCACHE_BYTES_PER_LINE 16
`define CFG_DCACHE_AUTO
`define ADDRESS_LOCK
`define LM32_I_PC_WIDTH 22
`define ADDRESS_LOCK
`define sramREAD_LATENCY 1
`define sramWRITE_LATENCY 1
`define sramSRAM_ADDR_WIDTH 19
`define sramSRAM_DATA_WIDTH 8
`define sramSRAM_BE_WIDTH 1
`define sramASRAM_WB_DAT_WIDTH 32
`define ADDRESS_LOCK
`define ebrEBR_WB_DAT_WIDTH 32
//`define ebrINIT_FILE_NAME "C:/cygwin/home/ws_lm32/jsp-1.4.4.1-full/hello_world/obj/jsp_hello_world.mem"
`define ebrINIT_FILE_NAME "C:/cygwin/home/ws_lm32/prj_lm32/obj/jsp_sample1.mem"
`define ebrINIT_FILE_FORMAT "hex"
`define LEDGPIO_WB_DAT_WIDTH 32
`define LEDGPIO_WB_ADR_WIDTH 4
`define ADDRESS_LOCK
`define LEDOUTPUT_PORTS_ONLY
`define LEDDATA_WIDTH 32'h8
`define GPIO_INGPIO_WB_DAT_WIDTH 32
`define GPIO_INGPIO_WB_ADR_WIDTH 4
`define ADDRESS_LOCK
`define GPIO_ININPUT_PORTS_ONLY
`define GPIO_INDATA_WIDTH 32'h8
`define TIMERS_WB_DAT_WIDTH 32
`define TIMERS_WB_ADR_WIDTH 4
`define ADDRESS_LOCK
`define TIMERPERIOD_NUM 32'h61a8
`define TIMERPERIOD_WIDTH 32'h20
`define TIMERWRITEABLE_PERIOD
`define TIMERREADABLE_SNAPSHOT
`define TIMERSTART_STOP_CONTROL
`define ADDRESS_LOCK
`define UART1UART_WB_DAT_WIDTH 8
//`define UART1UART_WB_ADR_WIDTH 4
`define UART1UART_WB_ADR_WIDTH 6
`define UART1CLK_IN_MHZ 0
`define UART1BAUD_RATE 9600
`define IB_SIZE 32'h10
`define OB_SIZE 32'h10
`define BLOCK_WRITE
`define BLOCK_READ
`define RXRDY_ENABLE
`define TXRDY_ENABLE
`define INTERRUPT_DRIVEN
`define CharIODevice
`define UART1LCR_DATA_BITS 8
`define UART1LCR_STOP_BITS 1
`define UART1FIFO
`define ADDRESS_LOCK
`define UART2UART_WB_DAT_WIDTH 8
//`define UART2UART_WB_ADR_WIDTH 4
`define UART2UART_WB_ADR_WIDTH 6
`define UART2CLK_IN_MHZ 0
`define UART2BAUD_RATE 115200
`define IB_SIZE 32'h10
`define OB_SIZE 32'h10
`define BLOCK_WRITE
`define BLOCK_READ
`define RXRDY_ENABLE
`define TXRDY_ENABLE
`define INTERRUPT_DRIVEN
`define CharIODevice
`define UART2LCR_DATA_BITS 8
`define UART2LCR_STOP_BITS 1
`define UART2FIFO
`endif // SYSTEM_CONF
